<#--<footer class="footer has-background-info">-->
<#--    <div class="content has-text-centered has-text-white">-->
<#--        <p>-->
<#--            Powwow - v0.1-->
<#--        </p>-->
<#--    </div>-->
<#--</footer>-->
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>
</body>
</html>