
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost/powwow