spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/powwow
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
