<nav class="level">
    <div class="level-left">
        <div class="level-item">
        </div>
    </div>

    <div class="level-right">
        <div class="level-item">
            <nav class="pagination is-right" role="navigation" aria-label="pagination">
                <a class="pagination-previous">Previous</a>
                <a class="pagination-next">Next page</a>
            </nav>
        </div>
    </div>
</nav>