<nav class="level">
    <div class="level-left">
        <div class="level-item">
            <a class="button" href="/">
                <span class="icon is-small">
                  <i class="fas fa-arrow-left"></i>
                </span>
                <span>Back</span>
            </a>
        </div>
    </div>

    <div class="level-right">
        <div class="level-item"><a class="button is-success">New</a></div>
    </div>
</nav>